# Generated by Django 6.0.1 on 2026-02-03 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "telefono",
                    models.CharField(help_text="Formato WhatsApp", max_length=20),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Detalles técnicos o especificaciones base",
                        null=True,
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("UNITARIO", "Unitario"),
                            ("METRO_CUADRADO", "Metro Cuadrado (m2)"),
                            ("METRO_LINEAL", "Metro Lineal (ml)"),
                        ],
                        default="UNITARIO",
                        max_length=20,
                    ),
                ),
                (
                    "valor_neto",
                    models.IntegerField(help_text="Valor base sin impuestos"),
                ),
                (
                    "iva",
                    models.IntegerField(editable=False, help_text="19% del valor neto"),
                ),
                (
                    "valor_bruto",
                    models.IntegerField(
                        editable=False, help_text="Precio final con IVA (Neto + IVA)"
                    ),
                ),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resumen",
                    models.CharField(
                        help_text="Título corto del trabajo", max_length=100
                    ),
                ),
                (
                    "detalles",
                    models.TextField(help_text="Detalles técnicos (Summernote)"),
                ),
                ("valor_total", models.IntegerField(help_text="Precio neto propuesto")),
                ("fecha_emision", models.DateField(default=django.utils.timezone.now)),
                (
                    "validez",
                    models.IntegerField(
                        default=15, help_text="Días de validez de la oferta"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("ACEPTADA", "Aceptada"),
                            ("EXPIRADA", "Expirada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resumen_pedido", models.CharField(max_length=100)),
                ("detalles_pedido", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("TERMINADO", "Terminado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("valor_venta", models.IntegerField()),
                ("valor_abonado", models.IntegerField(default=0)),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_entrega", models.DateField()),
                (
                    "imagen_referencia",
                    models.ImageField(blank=True, null=True, upload_to="pedidos/"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.IntegerField(help_text="Precio al momento de la venta"),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pedidos.producto",
                    ),
                ),
            ],
        ),
    ]
