# Generated by Django 6.0.1 on 2026-01-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "telefono",
                    models.CharField(help_text="Formato WhatsApp", max_length=20),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resumen_pedido", models.CharField(max_length=100)),
                ("detalles_pedido", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("TERMINADO", "Terminado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("valor_venta", models.IntegerField()),
                ("valor_abonado", models.IntegerField(default=0)),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_entrega", models.DateField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.cliente",
                    ),
                ),
            ],
        ),
    ]
