# Generated by Django 6.0.1 on 2026-01-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
