# Generated by Django 6.0.1 on 2026-01-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_cliente_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="imagen_referencia",
            field=models.ImageField(blank=True, null=True, upload_to="pedidos/"),
        ),
    ]
