# Generated by Django 6.0.1 on 2026-02-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_itemcotizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcotizacion",
            name="cantidad",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="cantidad",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
