# Generated by Django 6.0.1 on 2026-01-30 23:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_pedido_imagen_referencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resumen",
                    models.CharField(
                        help_text="Título corto del trabajo", max_length=100
                    ),
                ),
                (
                    "detalles",
                    models.TextField(help_text="Detalles técnicos (Summernote)"),
                ),
                ("valor_total", models.IntegerField(help_text="Precio neto propuesto")),
                ("fecha_emision", models.DateField(default=django.utils.timezone.now)),
                (
                    "validez",
                    models.IntegerField(
                        default=15, help_text="Días de validez de la oferta"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("ACEPTADA", "Aceptada"),
                            ("EXPIRADA", "Expirada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.cliente",
                    ),
                ),
            ],
        ),
    ]
