# Generated by Django 6.0.1 on 2026-02-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_alter_itemcotizacion_cantidad_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "tamano_mb",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tamaño ocupado en Megabytes",
                        max_digits=10,
                    ),
                ),
                ("total_pedidos", models.IntegerField(default=0)),
                ("total_clientes", models.IntegerField(default=0)),
                ("total_cotizaciones", models.IntegerField(default=0)),
                ("total_productos", models.IntegerField(default=0)),
            ],
        ),
    ]
