# Generated by Django 6.0.1 on 2026-02-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_cotizacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Detalles técnicos o especificaciones base",
                        null=True,
                    ),
                ),
                (
                    "precio_venta",
                    models.IntegerField(help_text="Precio unitario sugerido"),
                ),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
