# Generated by Django 6.0.1 on 2026-02-14 02:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_historialbd"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de Pago"),
                    ("PARCIAL", "Abono Parcial"),
                    ("PAGADO", "Pagado Total"),
                ],
                default="PENDIENTE",
                max_length=20,
                verbose_name="Estado Financiero",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="prioridad",
            field=models.IntegerField(default=1, verbose_name="Prioridad (1-3)"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pedidos.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="detalles_pedido",
            field=models.TextField(
                blank=True, null=True, verbose_name="Detalles Técnicos"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_PROCESO", "En Proceso"),
                    ("TERMINADO", "Terminado"),
                    ("ENTREGADO", "Entregado"),
                ],
                default="PENDIENTE",
                max_length=20,
                verbose_name="Estado Operativo",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="fecha_entrega",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Entrega Estimada"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="fecha_solicitud",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha Solicitud"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="imagen_referencia",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="referencias/",
                verbose_name="Imagen Referencia",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="resumen_pedido",
            field=models.CharField(max_length=150, verbose_name="Resumen del Pedido"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="valor_abonado",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Abono Inicial (LEGACY)"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="valor_venta",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Valor Total ($)"
            ),
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.PositiveIntegerField(verbose_name="Monto ($)")),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TRANSFERENCIA", "Transferencia Bancaria"),
                            ("DEBITO", "Tarjeta Débito"),
                            ("CREDITO", "Tarjeta Crédito"),
                        ],
                        default="EFECTIVO",
                        max_length=50,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "nota",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nota Interna"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="pedidos.pedido",
                        verbose_name="Pedido Asociado",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha"],
            },
        ),
    ]
