# Generated by Django 6.0.1 on 2026-02-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_pedido_creado_por_pedido_estado_pago_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="valor_abonado",
        ),
        migrations.AlterField(
            model_name="pedido",
            name="fecha_entrega",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Entrega"
            ),
        ),
    ]
